---
title: "CCS ENSO evaluation metrics"
author: "Victoria Froh & Jens Daniel Müller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Read this
this is the script to open the data
```{r read_data}

#loading packages
library(ncdf4)
library(stars)
library(tidyverse)
library(lubridate)
library(units)

#Path to the files:
path_ROMSv2RG_results <- 
 "/net/sea/work/loher/ROMS/Alk_enh_formatted_2024_08/regrid_2024_10/1979-2009_2/"

#opening specific nc file to get overview
# view_nc <- nc_open(paste0(path_ROMSv2RG_results,
#                      "isopycnal_monthly_2021_SanFrancisco.nc"))
# 
# print(view_nc)

#2x2 degree location boxes for each location + TrP 3.4 region:
#Columbia = 45N-47N, 124W-126W
#San Francisco = 36.5N-38.5N, 122.5W-124.5W
#Huntington = 32N-34N, 117W-119W
#Tropical Pacific = 5S-5N, 120W-170W

####################
#Sea Surface Temperature


# #All 3 regions colors
# ggplot() +
#  geom_stars(data = tropP_jan2010_temp, aes(fill = "#C77CFF")) +
#   geom_stars(data = colriv_jan2010_temp, aes(fill = "#F8766D")) +
#   geom_stars(data = sanfran_jan2010_temp, aes(fill = "#00BFC4")) +
#   geom_stars(data = hunt_jan2010_temp, aes(fill = "#7CAE00")) +
#   borders("world", colour = "gray80", fill = "gray80") +
#   labs(title = "CCS Test Regions",
#        x = "Longitude",
#        y = "Latitude") +
#   theme_minimal() +
#   scale_fill_identity(guide = "legend",
#                       labels = c("Tropical Pacific", "Columbia River", 
#                                  "San Francisco", "Huntington"),
#                       breaks = c("#C77CFF", "#F8766D", "#00BFC4", "#7CAE00")) +
#   coord_quickmap(xlim = c(-170,-115), ylim = c(-10, 49.5))

#
#42 year time series of historical monthly averages for all 4 locations
#
years_past <- 1979:2021
locations <- c("ColumbiaRiver", "SanFrancisco", "Huntington", "tropPacific")
annual_cycles <- list()
annual_monthly_sst_list <- list()

for (i in locations){
  #creating the 2x2 degree grid subsets for 3 CCS locations, tropP already set
  subset <- if (i == "ColumbiaRiver") {
    cbind(start = c(70, 40, 1, 1), count = c(16, 16, 1, 12))
  } else if (i == "SanFrancisco") {
    cbind(start = c(33, 39, 1, 1), count = c(16, 16, 1, 12))
  } else if (i == "Huntington") {
    cbind(start = c(50, 44, 1, 1), count = c(16, 16, 1, 12))
  } else if (i == "tropPacific") {
    cbind(start = c(1, 1, 1, 1), count = c(400, 80, 1, 12))
  }

  #reading in data for each location into a stars object
  annual_cycles[[i]] <- do.call(c, lapply(years_past, function(year)(
    suppressMessages(read_ncdf(paste0(path_ROMSv2RG_results,
                     "pactcs30_", year, "_monthly_", i, ".nc"),
              ncsub = subset,
              var = "temp",
              proxy = FALSE
  )))))
  
  #converting time dimensions, extracting year-month
  days_list <- st_get_dimension_values(annual_cycles[[i]], "time")
  annual_cycles[[i]] <- st_set_dimensions(annual_cycles[[i]], "time", 
                        values = format(ymd_hms(days_list),"%Y-%m"))
  
  #converting each stars object into a dataframe and cleaning up
  annual_cycles[[i]] <- annual_cycles[[i]] %>% 
    drop_units() %>% 
    as.data.frame(long = TRUE) %>% 
    select(-s_rho)
  
  #creating a new data frame with the monthly average over each region
  annual_monthly_sst_list[[i]] <- annual_cycles[[i]] %>% 
    group_by(time) %>% 
    summarise(mean_value = mean(temp, na.rm = TRUE), .groups = 'drop') %>% 
    rename(!!paste0(i, "_MonthlySST") := mean_value) 
}

#rearranging all location lists into a single data frame
annual_monthly_sst <- reduce(annual_monthly_sst_list, left_join, by = "time")

#saving theme formatting for all plots in this code
custom_theme <- theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 11),
        axis.text.y = element_text(size = 11),
        axis.ticks = element_line(linewidth = 0.3, color = "black"),
        axis.ticks.length = unit(-0.3, "cm"),
        axis.title.x = element_blank() ,
        axis.title.y = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.2, 0.08),
        legend.text = element_text(size = 10),
        legend.direction = "horizontal",
        legend.background = element_rect(color = "grey", linewidth = 0.25),
        panel.border = element_rect(color = "black", linewidth = 0.5, fill = NA))

#plotting all 4 time series of mean monthly SST
ggplot(data = annual_monthly_sst, aes(x = time, group = 1)) + 
  geom_line(aes(y = tropPacific_MonthlySST, color = "Tropical Pacific")) +
  geom_line(aes(y = ColumbiaRiver_MonthlySST, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_MonthlySST, color = "San Francisco")) +
  geom_line(aes(y = Huntington_MonthlySST, color = "Huntington")) +
  labs(title = "Monthly Mean Sea Surface Temperature", 
       y = "Mean Sea Surface Temperature (\u00B0C)", color = NULL) +
  scale_x_discrete(breaks = annual_monthly_sst$time[
    seq(which(annual_monthly_sst$time == "1980-01"), 
        nrow(annual_monthly_sst), by = 60)], #breaks every 5 years
    labels = substr(annual_monthly_sst$time[
      seq(which(annual_monthly_sst$time == "1980-01"), 
          nrow(annual_monthly_sst), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(limits = c(2, 30), breaks = seq(-10, 30, by = 5)) +
  scale_color_manual(values = c("Tropical Pacific" = "black", 
                                "Columbia River" = "#F8766D",
                                "San Francisco" = "#00BFC4",
                                "Huntington" = "#7CAE00")) +
  custom_theme

#clearing
rm(annual_cycles, days_list, subset, annual_monthly_sst_list, i)

#
#Calculating the anomaly index values (time series monthly sst - baseline)
#

#computing the mean over the full period for each month at each location
monthly_mean_baseline <- annual_monthly_sst %>%
  mutate(month = format(as.Date(paste0(time, "-01")), "%m")) %>% 
  group_by(month) %>% 
  summarise(ColumbiaRiver_basemonthlySST = mean(ColumbiaRiver_MonthlySST, 
                                        na.rm = TRUE),
    SanFrancisco_basemonthlySST = mean(SanFrancisco_MonthlySST, na.rm = TRUE),
    Huntington_basemonthlySST = mean(Huntington_MonthlySST, na.rm = TRUE),
    tropPacific_basemonthlySST = mean(tropPacific_MonthlySST, na.rm = TRUE),
    .groups = 'drop')

#Combining data, Extracting the month from the time and adding a column for it
annual_monthly_sst$month <- substr(annual_monthly_sst$time, 6, 7)

anomaly_sst_data <- merge(annual_monthly_sst, monthly_mean_baseline, 
                     by = "month") 

#calculate the anomaly for each location/month  (time series - base month mean)
for (place in locations) {
  anomaly_col <- paste0(place, "_SSTanomaly")
  anomaly_sst_data <- anomaly_sst_data %>% 
    mutate(!!anomaly_col := .data[[paste0(place, "_MonthlySST")]] - 
           .data[[paste0(place, "_basemonthlySST")]])
}

#reduce unneeded columns and sort chronologically
anomaly_sst <- anomaly_sst_data %>% 
  select(time, ColumbiaRiver_SSTanomaly, SanFrancisco_SSTanomaly, 
         Huntington_SSTanomaly, tropPacific_SSTanomaly) %>% 
  arrange(time)

#plot temperature anomalies
ggplot(data = anomaly_sst, aes(x = time, group = 1)) + 
  geom_line(aes(y = tropPacific_SSTanomaly, color = "Tropical Pacific"), 
            linetype = "dashed") +
  geom_line(aes(y = ColumbiaRiver_SSTanomaly, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_SSTanomaly, color = "San Francisco")) +
  geom_line(aes(y = Huntington_SSTanomaly, color = "Huntington")) +
  labs(title = "Monthly Sea Surface Temperature Anomalies", 
       y = "Sea Surface Temperature Anomaly (\u00B0C)", color = NULL) +
  scale_x_discrete(breaks = anomaly_sst$time[
    seq(which(anomaly_sst$time == "1980-01"), 
        nrow(anomaly_sst), by = 60)], #breaks every 5 years
    labels = substr(anomaly_sst$time[
      seq(which(anomaly_sst$time == "1980-01"), 
          nrow(anomaly_sst), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = seq(-4, 4, by = 1)) +
  scale_color_manual(values = c("Tropical Pacific" = "black", 
                                "Columbia River" = "#F8766D",
                                "San Francisco" = "#00BFC4",
                                "Huntington" = "#7CAE00")) +
  custom_theme

#clearing
rm(anomaly_sst_data, anomaly_col, place)

#
#Computing running annual mean for the sst anomaly
#(mean temp for one year starting that month)
#
anomaly_sst_ram <- anomaly_sst
for (spot in locations) {
  anom_col <- paste0(spot, "_SSTanomaly")
  anom_ram_col <- paste0(spot, "_SSTanom_ram")
  anomaly_sst_ram[[anom_ram_col]] <- NA #creates empty new column
  
  for (val in 1:(nrow(anomaly_sst) - 11)) { #will not calculate for 2021
    range <- anomaly_sst[[anom_col]][val:(val+11)] 
    #calculating and storing the running annual mean
    anomaly_sst_ram[[anom_ram_col]][val] <- mean(range, na.rm = TRUE)
    }
  }

#plotting
ggplot(data = anomaly_sst_ram, aes(x = time, group = 1)) + 
  geom_line(aes(y = tropPacific_SSTanom_ram, color = "Tropical Pacific"), 
            linetype = "dashed") +
  geom_line(aes(y = ColumbiaRiver_SSTanom_ram, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_SSTanom_ram, color = "San Francisco")) +
  geom_line(aes(y = Huntington_SSTanom_ram, color = "Huntington")) +
  labs(title = "Sea Surface Temperature Anomaly Running Annual Mean", 
       y = "Sea Surface Temperature Anomaly (\u00B0C)", color = NULL) +
  scale_x_discrete(breaks = anomaly_sst_ram$time[
    seq(which(anomaly_sst_ram$time == "1980-01"), 
        nrow(anomaly_sst_ram), by = 60)], #breaks every 5 years
    labels = substr(anomaly_sst_ram$time[
      seq(which(anomaly_sst_ram$time == "1980-01"), 
          nrow(anomaly_sst_ram), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(limits = c(-2.7, 2.7), breaks = seq(-2, 2, by = 1)) +
  scale_color_manual(values = c("Tropical Pacific" = "black", 
                                "Columbia River" = "#F8766D",
                                "San Francisco" = "#00BFC4",
                                "Huntington" = "#7CAE00")) +
  custom_theme

#Clearing
rm(anom_col, anom_ram_col, spot, val)

#
#Calculating correlation coefficients, pearson correlation test
#
cor.test(anomaly_sst$tropPacific_SSTanomaly, anomaly_sst$ColumbiaRiver_SSTanomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, anomaly_sst$SanFrancisco_SSTanomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, anomaly_sst$Huntington_SSTanomaly)

cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_sst_ram$ColumbiaRiver_SSTanom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_sst_ram$SanFrancisco_SSTanom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_sst_ram$Huntington_SSTanom_ram)


####################
#Temperature at 50m Depth

#
#42 year time series of historical monthly averages for all 4 locations
#
locations_2 <- c("ColumbiaRiver", "SanFrancisco", "Huntington")
annual_cycles <- list()
annual_monthly_t50_list <- list()

for (j in locations_2){
  #creating the 2x2 degree grid subsets for 3 CCS locations, tropP already set
  subset <- if (j == "ColumbiaRiver") {
    cbind(start = c(70, 40, 1), count = c(16, 16, 12))
  } else if (j == "SanFrancisco") {
    cbind(start = c(33, 39, 1), count = c(16, 16, 12))
  } else if (j == "Huntington") {
    cbind(start = c(50, 44, 1), count = c(16, 16, 12))
  } 

  #reading in data for each location into a stars object
  annual_cycles[[j]] <- do.call(c, lapply(years_past, function(year)(
    suppressMessages(read_ncdf(paste0(path_ROMSv2RG_results,
                     "pactcs30_", year, "_monthly_", j, "_50m.nc"),
              ncsub = subset,
              var = "temp",
              proxy = FALSE
  )))))
  
  #converting time dimensions, extracting year-month
  days_list <- st_get_dimension_values(annual_cycles[[j]], "time")
  annual_cycles[[j]] <- st_set_dimensions(annual_cycles[[j]], "time", 
                        values = format(ymd_hms(days_list),"%Y-%m"))
  
  #converting each stars object into a dataframe and cleaning up
  annual_cycles[[j]] <- annual_cycles[[j]] %>% 
    drop_units() %>% 
    as.data.frame(long = TRUE) 
  
  #creating a new data frame with the monthly average over each region
  annual_monthly_t50_list[[j]] <- annual_cycles[[j]] %>% 
    group_by(time) %>% 
    summarise(mean_value = mean(temp, na.rm = TRUE), .groups = 'drop') %>% 
    rename(!!paste0(j, "_MonthlyT_50m") := mean_value)
  
}
  
#rearranging all stored location lists into a single data frame
annual_monthly_t50 <- reduce(annual_monthly_t50_list, left_join, by = "time")

#plotting all 3 time series of mean monthly temperature at 50m depth
#setting color scheme for future plots
colors <- c("Tropical Pacific SST" = "black", "Columbia River" = "#F8766D",
            "San Francisco" = "#00BFC4", "Huntington" = "#7CAE00")

ggplot(data = annual_monthly_t50, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_MonthlyT_50m, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_MonthlyT_50m, color = "San Francisco")) +
  geom_line(aes(y = Huntington_MonthlyT_50m, color = "Huntington")) +
  geom_line(data = annual_monthly_sst, aes(
    x = time, y = tropPacific_MonthlySST, color = "Tropical Pacific SST", 
    group = 1)) +
  labs(title = "Monthly Mean Temperature at 50m", 
       y = "Mean Temperature (\u00B0C)", color = NULL) +
  scale_x_discrete(breaks = annual_monthly_t50$time[
    seq(which(annual_monthly_t50$time == "1980-01"), 
        nrow(annual_monthly_t50), by = 60)], #breaks every 5 years
    labels = substr(annual_monthly_t50$time[
      seq(which(annual_monthly_sst$time == "1980-01"), 
          nrow(annual_monthly_t50), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(limits = c(5, 30), breaks = seq(10, 30, by = 5)) +
  scale_color_manual(values = colors) +
  custom_theme + 
  theme(legend.position = c(0.2, 0.06))

#Clearing
rm(subset, annual_cycles, days_list, annual_monthly_t50_list, j)

#
#Calculating the anomaly index values (time series monthly T - baseline)
#

#computing the mean over the full period for each month at each location
monthly_mean_baseline_t50 <- annual_monthly_t50 %>% 
  mutate(month = format(as.Date(paste0(time, "-01")), "%m")) %>% 
  group_by(month) %>% 
  summarise(ColumbiaRiver_basemonthlyT50 = mean(ColumbiaRiver_MonthlyT_50m, 
                                        na.rm = TRUE),
    SanFrancisco_basemonthlyT50 = mean(SanFrancisco_MonthlyT_50m, na.rm = TRUE),
    Huntington_basemonthlyT50 = mean(Huntington_MonthlyT_50m, na.rm = TRUE),
    .groups = 'drop')

#Combining data, extracting the month from the time and adding a column for it
annual_monthly_t50$month <- substr(annual_monthly_t50$time, 6, 7)

anomaly_t50_data <- merge(annual_monthly_t50, monthly_mean_baseline_t50, 
                     by = "month") 

#calculate the anomaly for each location/month  (time series - base month mean)
for (place in locations_2) {
  anomaly_col <- paste0(place, "_T50anomaly")
  anomaly_t50_data <- anomaly_t50_data %>% 
    mutate(!!anomaly_col := .data[[paste0(place, "_MonthlyT_50m")]] - 
           .data[[paste0(place, "_basemonthlyT50")]])
}

#reduce unneeded columns and sort chronologically
anomaly_t50 <- anomaly_t50_data %>% 
  select(time, ColumbiaRiver_T50anomaly, SanFrancisco_T50anomaly, 
         Huntington_T50anomaly) %>% 
  arrange(time)

#plot temperature anomalies
ggplot(data = anomaly_t50, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_T50anomaly, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_T50anomaly, color = "San Francisco")) +
  geom_line(aes(y = Huntington_T50anomaly, color = "Huntington")) +
  geom_line(data = anomaly_sst, 
            aes(x = time, y = tropPacific_SSTanomaly, 
                color = "Tropical Pacific SST", group = 1), linetype = "dashed") +
  labs(title = "Monthly 50m Temperature Anomalies", 
       y = "Temperature Anomaly (\u00B0C)", color = NULL) +
  scale_x_discrete(breaks = anomaly_t50$time[
    seq(which(anomaly_t50$time == "1980-01"), 
        nrow(anomaly_t50), by = 60)], #breaks every 5 years
    labels = substr(anomaly_t50$time[
      seq(which(anomaly_t50$time == "1980-01"), 
          nrow(anomaly_t50), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(limits = c(-4.4, 4.4), breaks = seq(-4, 4, by = 1)) +
  scale_color_manual(values = colors) +
  custom_theme

#Clearing
rm(anomaly_t50_data, place, anomaly_col)

#
#Computing running annual mean for the 50m T anomaly
#(mean temp for one year starting that month)
#
anomaly_t50_ram <- anomaly_t50
for (spot in locations_2) {
  anom_col <- paste0(spot, "_T50anomaly")
  anom_ram_col <- paste0(spot, "_T50anom_ram")
  anomaly_t50_ram[[anom_ram_col]] <- NA #creates empty new column
  
  for (val in 1:(nrow(anomaly_t50) - 11)) { #will not calculate for 2021
    range <- anomaly_t50[[anom_col]][val:(val+11)] 
    #calculating and storing the running annual mean
    anomaly_t50_ram[[anom_ram_col]][val] <- mean(range, na.rm = TRUE)
    }
  }

#plotting
ggplot(data = anomaly_t50_ram, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_T50anom_ram, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_T50anom_ram, color = "San Francisco")) +
  geom_line(aes(y = Huntington_T50anom_ram, color = "Huntington")) +
  geom_line(data = anomaly_sst_ram, 
            aes(x = time, y = tropPacific_SSTanom_ram, 
                color = "Tropical Pacific SST", group = 1), linetype = "dashed") +
  labs(title = "50m Temperature Anomaly Running Annual Mean", 
       y = "Temperature Anomaly (\u00B0C)", color = NULL) +
  scale_x_discrete(breaks = anomaly_t50_ram$time[
    seq(which(anomaly_t50_ram$time == "1980-01"), 
        nrow(anomaly_t50_ram), by = 60)], #breaks every 5 years
    labels = substr(anomaly_t50_ram$time[
      seq(which(anomaly_t50_ram$time == "1980-01"), 
          nrow(anomaly_t50_ram), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(limits = c(-2.6, 2.6), breaks = seq(-2, 2, by = 1)) +
  scale_color_manual(values = colors) +
  custom_theme

#Clearing
rm(anom_col, anom_ram_col, spot, val)

#
#Calculating correlation coefficients, pearson correlation test
#
cor.test(anomaly_sst$tropPacific_SSTanomaly, anomaly_t50$ColumbiaRiver_T50anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, anomaly_t50$SanFrancisco_T50anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, anomaly_t50$Huntington_T50anomaly)

cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_t50_ram$ColumbiaRiver_T50anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_t50_ram$SanFrancisco_T50anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_t50_ram$Huntington_T50anom_ram)


####################
#Isopycnal 20kg/m3 Depth and Salinity

#
#42 year time series of historical monthly averages for all 4 locations
#
annual_cycles <- list()
annual_monthly_iso26_list <- list()

for (j in locations_2){
  #creating the 2x2 degree grid subsets for 3 CCS locations, tropP already set
  subset <- if (j == "ColumbiaRiver") {
    cbind(start = c(70, 40, 1), count = c(16, 16, 12))
  } else if (j == "SanFrancisco") {
    cbind(start = c(33, 39, 1), count = c(16, 16, 12))
  } else if (j == "Huntington") {
    cbind(start = c(50, 44, 1), count = c(16, 16, 12))
  } 

  #reading in data for each location into a stars object
  annual_cycles[[j]] <- do.call(c, lapply(years_past, function(year)(
    suppressMessages(read_ncdf(paste0(path_ROMSv2RG_results,
                     "isopycnal_monthly_", year, "_", j, ".nc"),
              ncsub = subset,
              var = c("depth_26", "salt_26"),
              proxy = FALSE
  )))))
  
  #converting time dimensions, extracting year-month
  days_list <- st_get_dimension_values(annual_cycles[[j]], "time")
  annual_cycles[[j]] <- st_set_dimensions(annual_cycles[[j]], "time", 
                        values = format(ymd_hms(days_list),"%Y-%m"))
  
  #converting each stars object into a dataframe and cleaning up
  annual_cycles[[j]] <- annual_cycles[[j]] %>% 
    drop_units() %>% 
    as.data.frame(long = TRUE) 
  
  #Weird values showing up in SF, need to filter out
  if (j == "SanFrancisco") {
  annual_cycles[[j]] <- annual_cycles[[j]] %>%
    filter(depth_26 >= 1, salt_26 >= 1)
}
  
  #creating a new data frame with the monthly average over each region
  annual_monthly_iso26_list[[j]] <- annual_cycles[[j]] %>% 
    group_by(time) %>% 
    summarise(mean_depth_26 = mean(depth_26, na.rm = TRUE),
    mean_salt_26 = mean(salt_26, na.rm = TRUE), .groups = 'drop') %>% 
    rename(!!paste0(j, "_MonthlyIso26_Depth") := mean_depth_26,
           !!paste0(j, "_MonthlyIso26_Sal") := mean_salt_26)
  
}

#rearranging all stored location lists into a single data frame
annual_monthly_iso26 <- reduce(annual_monthly_iso26_list, left_join, by = "time")

#plotting all 3 time series of mean depth of the 26kg isopycnal
#get TrP SST index to match scale
ggplot(data = annual_monthly_iso26, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_MonthlyIso26_Depth, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_MonthlyIso26_Depth, color = "San Francisco")) +
  geom_line(aes(y = Huntington_MonthlyIso26_Depth, color = "Huntington")) +
  geom_line(data = annual_monthly_sst, 
            aes(x = time, y = tropPacific_MonthlySST * 18 - 400, #scaling
                color = "Tropical Pacific SST", group = 1), linetype = "dashed") +
  labs(title = expression("Depth of 26 kg/m"^3*" Isopycnal"), y = "Depth (m)", 
       color = NULL) +
  scale_x_discrete(breaks = annual_monthly_iso26$time[
    seq(which(annual_monthly_iso26$time == "1980-01"), 
        nrow(annual_monthly_iso26), by = 60)], #breaks every 5 years
    labels = substr(annual_monthly_iso26$time[
      seq(which(annual_monthly_iso26$time == "1980-01"), 
          nrow(annual_monthly_iso26), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_reverse(
    limits = c(145, 15), breaks = seq(20, 140, by = 20), sec.axis = 
      sec_axis(~ (. + 400)/ 18, 
               name = "Tropical Pacific Sea Surface Temperature (°C)", 
               breaks = seq(23, 30, by = 1))) +
  scale_color_manual(values = colors) +
  custom_theme

#plotting all 3 time series of mean salinity of the 26kg isopycnal
ggplot(data = annual_monthly_iso26, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_MonthlyIso26_Sal, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_MonthlyIso26_Sal, color = "San Francisco")) +
  geom_line(aes(y = Huntington_MonthlyIso26_Sal, color = "Huntington")) +
  geom_line(data = annual_monthly_sst, 
            aes(x = time, y = tropPacific_MonthlySST * 0.13 + 30,
                color = "Tropical Pacific SST", group = 1), linetype = "dashed") +
  labs(title = expression("Salinity of 26 kg/m"^3*" Isopycnal"), y = "Depth (m)",
       color = NULL) +
  scale_x_discrete(breaks = annual_monthly_iso26$time[
    seq(which(annual_monthly_iso26$time == "1980-01"), 
        nrow(annual_monthly_iso26), by = 60)], #breaks every 5 years
    labels = substr(annual_monthly_iso26$time[
      seq(which(annual_monthly_iso26$time == "1980-01"), 
          nrow(annual_monthly_iso26), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(
    limits = c(32.95, 34.05), breaks = seq(33, 34, by = 0.25), 
    sec.axis = sec_axis(~ (. - 30)/ 0.13, 
                        name = "Tropical Pacific Sea Surface Temperature (°C)")) +
  scale_color_manual(values = colors) +
  custom_theme

#Clearing
rm(subset, annual_cycles, days_list, annual_monthly_iso26_list, j)

#
#Calculating the anomaly index values (time series monthly T - baseline)
#

#computing the mean over the full period for each month at each location
monthly_mean_baseline_iso26 <- annual_monthly_iso26 %>% 
  mutate(month = format(as.Date(paste0(time, "-01")), "%m")) %>% 
  group_by(month) %>% 
  summarise(ColumbiaRiver_basemonthly26dep = mean(ColumbiaRiver_MonthlyIso26_Depth, 
                                        na.rm = TRUE),
            ColumbiaRiver_basemonthly26sal = mean(ColumbiaRiver_MonthlyIso26_Sal, 
                                        na.rm = TRUE),
            SanFrancisco_basemonthly26dep = mean(SanFrancisco_MonthlyIso26_Depth, 
                                               na.rm = TRUE), 
            SanFrancisco_basemonthly26sal = mean(SanFrancisco_MonthlyIso26_Sal, 
                                               na.rm = TRUE),
            Huntington_basemonthly26dep = mean(Huntington_MonthlyIso26_Depth, 
                                             na.rm = TRUE), 
            Huntington_basemonthly26sal = mean(Huntington_MonthlyIso26_Sal, 
                                             na.rm = TRUE),, .groups = 'drop')

#Combining, extracting the month from the time and adding a column for it
annual_monthly_iso26$month <- substr(annual_monthly_iso26$time, 6, 7)

anomaly_iso26_data <- merge(annual_monthly_iso26, monthly_mean_baseline_iso26, 
                     by = "month") 

#calculate the anomaly for each location/month  (time series - base month mean)
for (place in locations_2) {
  anomaly_col <- paste0(place, "_iso26Dep_anomaly")
  anomaly_iso26_data <- anomaly_iso26_data %>% 
    mutate(!!anomaly_col := .data[[paste0(place, "_MonthlyIso26_Depth")]] - 
           .data[[paste0(place, "_basemonthly26dep")]])
}

for (place2 in locations_2) {
  anomaly_col <- paste0(place2, "_iso26Sal_anomaly")
  anomaly_iso26_data <- anomaly_iso26_data %>% 
    mutate(!!anomaly_col := .data[[paste0(place2, "_MonthlyIso26_Sal")]] - 
           .data[[paste0(place2, "_basemonthly26sal")]])
}

#reduce unneeded columns and sort chronologically
anomaly_iso26 <- anomaly_iso26_data %>% 
  select(time, ColumbiaRiver_iso26Dep_anomaly, ColumbiaRiver_iso26Sal_anomaly, 
         SanFrancisco_iso26Dep_anomaly, SanFrancisco_iso26Sal_anomaly, 
         Huntington_iso26Dep_anomaly, Huntington_iso26Sal_anomaly) %>% 
  arrange(time)

#plot anomalies
#get TrP SST index to match scale
depanom_scale <- max(anomaly_iso26$ColumbiaRiver_Iso26Dep_anomaly, 
                        anomaly_iso26$SanFrancisco_iso26Dep_anomaly, 
                        anomaly_iso26$Huntington_iso26Dep_anomaly) / 
                    max(anomaly_sst$tropPacific_SSTanomaly)

ggplot(data = anomaly_iso26, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_iso26Dep_anomaly, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_iso26Dep_anomaly, color = "San Francisco")) +
  geom_line(aes(y = Huntington_iso26Dep_anomaly, color = "Huntington")) +
  geom_line(data = anomaly_sst, 
            aes(x = time, y = tropPacific_SSTanomaly * depanom_scale, 
                color = "Tropical Pacific SST", group = 1), linetype = "dashed") +
  labs(title = expression("Depth Anomalies of 26kg/m"^3*" Isopycnal"),
       y = "Depth Anomaly (m)", color = NULL) +
  scale_x_discrete(breaks = anomaly_iso26$time[
    seq(which(anomaly_iso26$time == "1980-01"), 
        nrow(anomaly_iso26), by = 60)], #breaks every 5 years
    labels = substr(anomaly_iso26$time[
      seq(which(anomaly_iso26$time == "1980-01"), 
          nrow(anomaly_iso26), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_reverse(
    limits = c(52, -45), breaks = seq(-40, 40, by = 10),
    sec.axis = sec_axis(~ . / depanom_scale, 
                        name = "Tropical Pacific Sea Surface Temperature (°C)", 
                        breaks = seq(-3, 3, by = 1))) + 
  scale_color_manual(values = colors) +
  custom_theme + 
  theme(legend.position = c(0.2, 0.945))

ggplot(data = anomaly_iso26, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_iso26Sal_anomaly, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_iso26Sal_anomaly, color = "San Francisco")) +
  geom_line(aes(y = Huntington_iso26Sal_anomaly, color = "Huntington")) +
  # geom_line(data = anomaly_sst, aes(x = time, y = tropPacific_SSTanomaly,
  #                                          color = "Tropical Pacific SST",
  #                                          group = 1)) +
  labs(title = expression("Salinity Anomalies of 26kg/m"^3*" Isopycnal"),
       y = "Salinity Anomaly (psu)", color = NULL) +
  scale_x_discrete(breaks = anomaly_iso26$time[
    seq(which(anomaly_iso26$time == "1980-01"), 
        nrow(anomaly_iso26), by = 60)], #breaks every 5 years
    labels = substr(anomaly_iso26$time[
      seq(which(anomaly_iso26$time == "1980-01"), 
          nrow(anomaly_iso26), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_continuous(
    limits = c(-0.27, 0.27), breaks = seq(-0.2, 0.2, by = 0.1)) +
  scale_color_manual(values = colors) +
  custom_theme + 
  theme(legend.position = c(0.16, 0.945))


#Clearing
rm(anomaly_iso26_data, place, place2, anomaly_col)

#
#Computing running annual mean
#(mean for one year starting that month)
#
anomaly_iso26_ram <- anomaly_iso26
for (spot in locations_2) {
  anom_col <- paste0(spot, "_iso26Dep_anomaly")
  anom_ram_col <- paste0(spot, "_iso26Dep_anom_ram")
  anomaly_iso26_ram[[anom_ram_col]] <- NA #creates empty new column
  
  for (val in 1:(nrow(anomaly_iso26) - 11)) { #will not calculate for 2021
    range <- anomaly_iso26[[anom_col]][val:(val+11)] 
    #calculating and storing the running annual mean
    anomaly_iso26_ram[[anom_ram_col]][val] <- mean(range, na.rm = TRUE)
    }
}
for (spot2 in locations_2) {
  anom_col <- paste0(spot2, "_iso26Sal_anomaly")
  anom_ram_col <- paste0(spot2, "_iso26Sal_anom_ram")
  anomaly_iso26_ram[[anom_ram_col]] <- NA #creates empty new column
  
  for (val in 1:(nrow(anomaly_iso26) - 11)) { #will not calculate for 2021
    range <- anomaly_iso26[[anom_col]][val:(val+11)] 
    #calculating and storing the running annual mean
    anomaly_iso26_ram[[anom_ram_col]][val] <- mean(range, na.rm = TRUE)
    }
  }

#plotting
#get TrP SST indice to match scale
depanomram_scale <- max(anomaly_iso26_ram$ColumbiaRiver_iso26Dep_anom_ram, 
                        anomaly_iso26_ram$SanFrancisco_iso26Dep_anom_ram, 
                        anomaly_iso26_ram$Huntington_iso26Dep_anom_ram, 
                        na.rm = TRUE) / 
                    max(anomaly_sst_ram$tropPacific_SSTanom_ram, na.rm = TRUE)

ggplot(data = anomaly_iso26_ram, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_iso26Dep_anom_ram, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_iso26Dep_anom_ram, color = "San Francisco")) +
  geom_line(aes(y = Huntington_iso26Dep_anom_ram, color = "Huntington")) +
  geom_line(data = anomaly_sst_ram, 
            aes(x = time, y = tropPacific_SSTanom_ram * depanomram_scale, 
                color = "Tropical Pacific SST", group = 1), linetype = "dashed") +
  labs(title = 
         expression("Depth Anomaly 26kg/m"^3*" Isopycnal Running Annual Mean"), 
       y = "Depth Anomaly (m)", color = NULL) +
  scale_x_discrete(breaks = anomaly_iso26_ram$time[
    seq(which(anomaly_iso26_ram$time == "1980-01"), 
        nrow(anomaly_iso26_ram), by = 60)], #breaks every 5 years
    labels = substr(anomaly_iso26_ram$time[
      seq(which(anomaly_iso26_ram$time == "1980-01"), 
          nrow(anomaly_iso26_ram), by = 60)], 1, 4)) + # Minor breaks every year
  scale_y_reverse(
    sec.axis = sec_axis(~ . / depanomram_scale, 
                        name = "Tropical Pacific Sea Surface Temperature (°C)")) + 
  scale_color_manual(values = colors) +
  custom_theme + 
  theme(legend.position = c(0.2, 0.945))

ggplot(data = anomaly_iso26_ram, aes(x = time, group = 1)) + 
  geom_line(aes(y = ColumbiaRiver_iso26Sal_anom_ram, color = "Columbia River")) +
  geom_line(aes(y = SanFrancisco_iso26Sal_anom_ram, color = "San Francisco")) +
  geom_line(aes(y = Huntington_iso26Sal_anom_ram, color = "Huntington")) +
  # geom_line(data = anomaly_sst_ram, aes(x = time, y = tropPacific_SSTanom_ram, 
  #                                          color = "Tropical Pacific SST", 
  #                                          group = 1)) +
  labs(title = 
         expression("Salinity Anomaly 26kg/m"^3*" Isopycnal Running Annual Mean"), 
       y = "Salinity Anomaly (psu)", color = NULL) +
  scale_x_discrete(breaks = anomaly_iso26_ram$time[
    seq(which(anomaly_iso26_ram$time == "1980-01"), 
        nrow(anomaly_iso26_ram), by = 60)], #breaks every 5 years
    labels = substr(anomaly_iso26_ram$time[
      seq(which(anomaly_iso26_ram$time == "1980-01"), 
          nrow(anomaly_iso26_ram), by = 60)], 1, 4)) + # Minor breaks every year
  scale_color_manual(values = colors) +
  custom_theme +
  theme(legend.position = c(0.16, 0.945))

#Clearing
rm(anom_col, anom_ram_col, spot, val)

#
#Calculating correlation coefficients, pearson correlation test
#
cor.test(anomaly_sst$tropPacific_SSTanomaly,
         anomaly_iso26$ColumbiaRiver_iso26Dep_anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, 
         anomaly_iso26$SanFrancisco_iso26Dep_anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, 
         anomaly_iso26$Huntington_iso26Dep_anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly,
         anomaly_iso26$ColumbiaRiver_iso26Sal_anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, 
         anomaly_iso26$SanFrancisco_iso26Sal_anomaly)
cor.test(anomaly_sst$tropPacific_SSTanomaly, 
         anomaly_iso26$Huntington_iso26Sal_anomaly)

cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_iso26_ram$ColumbiaRiver_iso26Dep_anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_iso26_ram$SanFrancisco_iso26Dep_anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_iso26_ram$Huntington_iso26Dep_anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_iso26_ram$ColumbiaRiver_iso26Sal_anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_iso26_ram$SanFrancisco_iso26Sal_anom_ram)
cor.test(anomaly_sst_ram$tropPacific_SSTanom_ram,
         anomaly_iso26_ram$Huntington_iso26Sal_anom_ram)
```

vhjgvj


```{r plot_data}

```

