---
title: "Data practice"
author: "Victoria Froh & Jens Daniel Müller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Read this
Practice working with OAE ROMS data

```{r setup, message=FALSE, results='hide'}

#loading packages
library(ncdf4)
library(tidync)
library(stars)
library(tidyverse)
library(seacarb)
library(metR)

#For the regridded standard files, path:
path_ROMSv2RG_results <- 
 "/net/sea/work/loher/ROMS/Alk_enh_formatted_2024_08/"

#opening specific nc file to get overview (Columbia site, 1x)
view_nc <- nc_open(paste0(path_ROMSv2RG_results,
                     "ColumbiaRiver/ColumbiaRiver_2010-2015_1x.nc"))

print(view_nc)

```

```{r load_data_with_stars, results='hide', message=FALSE}

#filtering for just one variable w/ stars package + time and depth slice
nc_alk <- read_ncdf(paste0(path_ROMSv2RG_results,
                     "ColumbiaRiver/ColumbiaRiver_2010-2015_1x.nc"),
           var = "Alk",
           ncsub = cbind(start = c(1, 1, 1, 1), count = c(96, 88, 1, 1)
             ),
           proxy = FALSE #need this on to override the proxy format
          )

nc_dic <- read_ncdf(paste0(path_ROMSv2RG_results,
                     "ColumbiaRiver/ColumbiaRiver_2010-2015_1x.nc"),
           var = "DIC",
           ncsub = cbind(start = c(1, 1, 1, 1), count = c(96, 88, 1, 1)
             ),
           proxy = FALSE #need this on to override the proxy format
          )

#creating a blank plot and loading in the nc data layers 
ggplot() +
 geom_stars(data = nc_alk, aes(fill = Alk)) +
  labs(title = "Columbia River Surface Alkalinity @ T1",
       x = "Longitude",
       y = "Latitude") +
  theme_bw() + 
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0)

ggplot() +
 geom_stars(data = nc_dic, aes(fill = DIC)) +
  labs(title = "Columbia River Surface DIC @ T1",
       x = "Longitude",
       y = "Latitude") +
  theme_bw() + 
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0)

```

```{r  load_data_with_tidync, results='hide', message=FALSE}

nc <- tidync(paste0(path_ROMSv2RG_results,
                     "ColumbiaRiver/ColumbiaRiver_2010-2015_1x.nc"))

#filtering nc file for just the surface @ the first time index, outputting tbl_df
alk_surface_t1 <- nc %>%
  hyper_filter(depth = index == 1, time = index == 1) %>% 
  hyper_tibble(select_var = c("Alk"))

dic_surface_t1 <- nc %>%
  hyper_filter(depth = index == 1, time = index == 1) %>% 
  hyper_tibble(select_var = c("DIC"))

#plotting variables
ggplot(data = alk_surface_t1) + 
  geom_tile(aes(lon, lat, fill = Alk)) +
  labs(title = "Columbia River Surface Alkalinity @ T1", 
       x = "Longitude", y = "Latitude") + 
  theme_bw() +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0)

ggplot(data = dic_surface_t1) + 
  geom_tile(aes(lon, lat, fill = DIC)) +
  labs(title = "Columbia River Surface DIC @ T1", 
       x = "Longitude", y = "Latitude") + 
  theme_bw() +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0)

```

```{r seacarb_calc, results='hide', message=FALSE}

#load in data from tidync file in main active grid w/ T1 surface slice
surface_data <- nc %>%
     hyper_filter(depth = index == 1, time = index == 1) %>% 
     hyper_tibble(force = TRUE)

#loading in data in other grid ie surface variables
surface_data_pco2 <- nc %>%
  activate("D1,D2,D0") %>% #activating surface grid for PCO2OC variable
  hyper_filter(time = index == 1) %>% 
  hyper_tibble(select_var = c("PCO2OC"), #  produces a tibble object
                  force = TRUE)

merged_surface <- full_join(surface_data, surface_data_pco2)

#running carb to produce the pCO2 values
merged_surface_orig <-
  merged_surface %>%
  #head(6) %>% #testing subsset
  drop_na() %>% #drops all rows with an NA
  mutate(
    pco2_calc = carb(
      flag = 15,
      var1 = Alk * 1e-6 / 1.02518,
      var2 = DIC * 1e-6 / 1.02518,
      S = salt,
      T = temp,
      P = 0,
      #surface = 0
      Pt = PO4 * 1e-6 / 1.02518,
      Sit = SiO3 * 1e-6 / 1.02518,
      kf="dg",
      k1k2="m06",
      ks="d"
    )$pCO2 #to just save the pco2 output
  )

#plotting pco2
ggplot(data = merged_surface_orig) + 
  geom_tile(aes(lon, lat, fill = pco2_calc)) +
  labs(title = "Columbia River Calculated PCO2 @ T1", 
       x = "Longitude", y = "Latitude", fill = "pCO2 (µatm)") + 
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0)

#Comparing Outputs

#New dataframe w/ reorganized pCO2 data
pco2_compare <- merged_surface_orig %>% 
  select(lon, lat, pco2_calc, PCO2OC) %>% 
  pivot_longer(
    cols = c(pco2_calc, PCO2OC),
    names_to = "Variant",
    values_to = "pCO2"
  )

#Plotting side-by-side comparison  
ggplot(data = pco2_compare) + 
  geom_tile(aes(lon, lat, fill = pCO2)) +
  facet_grid(cols = vars(Variant)) + 
  labs(title = "Calculated pCO2 vs Model pCO2", 
       x = "Longitude", y = "Latitude", fill = "pCO2 (µatm)") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  coord_quickmap(expand = 0) + 
  scale_fill_viridis_c()
  

#New df w/ the difference between model and calculated pCO2
pco2_delta <- merged_surface_orig %>% 
  select(lon, lat, pco2_calc, PCO2OC) %>% 
  mutate(dpco2 = PCO2OC - pco2_calc)

#Plotting difference
ggplot(data = pco2_delta) +
  geom_tile(aes(lon, lat, fill = dpco2)) + 
  labs(title = "Model pCO2 - Calculated pCO2", 
       x = "Longitude", y = "Latitude", fill = "dpCO2 (µatm)") +
  scale_fill_divergent() + 
  coord_quickmap(expand = 0) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()

```

```{r seacarb_perturbation_calc, results='hide', message=FALSE}

#Perturbation of 10 mmol Alk/m^3 in all grid cells
surface_pert <- 
  merged_surface_orig %>%
  #head(6) %>% #testing subsset
  drop_na() %>% #drops all rows with an NA
  mutate(
    pco2_calc_pert = carb(
      flag = 15,
      var1 = (Alk + 10) * 1e-6 / 1.02518,
      var2 = DIC * 1e-6 / 1.02518,
      S = salt,
      T = temp,
      P = 0,
      Pt = PO4 * 1e-6 / 1.02518,
      Sit = SiO3 * 1e-6 / 1.02518,
      kf="dg",
      k1k2="m06",
      ks="d"
    )$pCO2
  )

#New dataframe w/ reorganized pCO2_pert data to compare
pco2_pert_compare <- surface_pert %>% 
  select(lon, lat, pco2_calc_pert, pco2_calc) %>% 
  pivot_longer(
    cols = c(pco2_calc_pert, pco2_calc),
    names_to = "Variant",
    values_to = "pCO2"
  )

#Plotting side-by-side comparison  
ggplot(data = pco2_pert_compare) + 
  geom_tile(aes(lon, lat, fill = pCO2)) +
  facet_grid(cols = vars(Variant)) + 
  labs(title = "Initial pCO2 vs pCO2 after Added Alkalinity", 
       x = "Longitude", y = "Latitude", fill = "pCO2 (µatm)") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  coord_quickmap(expand = 0) + 
  scale_fill_viridis_c()
  

#New df w/ the difference in pCO2 after Alk perturbation
pco2_pert_delta <- full_join(surface_pert, pco2_delta) %>% 
  select(lon, lat, pco2_calc_pert, pco2_calc) %>% 
  mutate(dpco2 = pco2_calc_pert - pco2_calc)

#Plotting difference
ggplot(data = pco2_pert_delta) +
  geom_tile(aes(lon, lat, fill = dpco2)) + 
  labs(title = "Difference in pCO2 after Added Alkalinity", 
       x = "Longitude", y = "Latitude", fill = "dpCO2 (µatm)") +
  #scale_fill_divergent() + 
  scale_fill_viridis_c(option = "magma") +
  coord_quickmap(expand = 0) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()

#Alooking at how DIC changes for perturbation with constant pCO2
surface_pert_dic <- 
  merged_surface_orig %>%
  #head(6) %>% #testing subsset
  drop_na() %>% #drops all rows with an NA
  mutate(
    DIC_pert = carb(
      flag = 24,
      var1 = pco2_calc, # for consistency, use the calculate pCO2 here, 
      #otherwise you compute a DIC perturbation that is partly due to 
      #differences in the computational routines (vs the model)
      var2 = (Alk + 10) * 1e-6 / 1.02518,
      S = salt,
      T = temp,
      P = 0,
      #surface = 0
      Pt = PO4 * 1e-6 / 1.02518,
      Sit = SiO3 * 1e-6 / 1.02518,
      kf="dg",
      k1k2="m06",
      ks="d"
    )$DIC #to just save the pco2 output
    * 1.02518 * 1e6 #converting back to model units of mmol/m^3
  )

#New dataframe w/ reorganized DIC data to compare
dic_pert_compare <- surface_pert_dic %>% 
  select(lon, lat, DIC_pert, DIC) %>% 
  pivot_longer(
    cols = c(DIC_pert, DIC),
    names_to = "Variant",
    values_to = "DIC"
  )

#Plotting side-by-side comparison  
ggplot(data = dic_pert_compare) + 
  geom_tile(aes(lon, lat, fill = DIC)) +
  facet_grid(cols = vars(Variant)) + 
  labs(title = "Initial Model DIC vs DIC after Added Alkalinity", 
       x = "Longitude", y = "Latitude", fill = "DIC (mmol/m^3)") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  coord_quickmap(expand = 0) + 
  scale_fill_viridis_c()
  
#New df w/ the difference in DIC after Alk perturbation
dic_pert_delta <- surface_pert_dic %>% 
  select(lon, lat, DIC_pert, DIC) %>% 
  mutate(dDIC = DIC_pert - DIC)

#Plotting difference
ggplot(data = dic_pert_delta) +
  geom_tile(aes(lon, lat, fill = dDIC)) + 
  labs(title = "Difference in DIC after Added Alkalinity", 
       x = "Longitude", y = "Latitude", fill = "dDIC (mmol/m^3)") +
  #scale_fill_divergent() + 
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_quickmap(expand = 0) + 
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```

